### ISSUE TITLE
[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.

### ISSUE THREAD

**Issue by CameliaMocanu** [awezmm/FiberAI#2]
Hi,

I tried to run the code on both windows and macbook, however on windows it was quite difficult to install and in the end I still did not manage to do it properly (having CUDA runtime error). On macbook I managed to run it successfully, however, I am getting this error:

"
Importing Modules
Building Predictor
Analyzing Images
[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.
Traceback (most recent call last):
  File "/Users/cmocanu/Downloads/FiberAI-main/main.py", line 552, in <module>
    main_analyze(image_files, args.out)
  File "/Users/cmocanu/Downloads/FiberAI-main/main.py", line 503, in main_analyze
    currFiberLengths = currCSVData[:,[2,3]]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
"
I am running it on 2 channel images 1024 x 1024 in size. My build is MacBook Pro (13-inch, M1, 2020) with 8gb RAM.

Thank you!

**Comment by CameliaMocanu** [comment]
Hi,

I realised the issue was that my images were 16bit, once I made the images 8bit the code worked like a charm. I am still getting the hardware error, but the code runs regardless and gives good output.

Thanks
C
